In [24]:
import pandas as pd

In [28]:
x ='./hackathon-online-malware-classification/malware_api_data/malware_api_data.csv'

In [29]:
import pandas as pd

try:
    df = pd.read_csv(x, header=None, sep='\t')  # Try tab as delimiter
except pd.errors.ParserError:
    try:
        df = pd.read_csv(x, header=None, sep=',')  # Try semicolon as delimiter
    except pd.errors.ParserError:
        # Handle other potential delimiters or raise an error
        print("Error parsing CSV file. Please check the file format and delimiter.")

In [30]:
df

                                                     0
0    06f73f2da4ecd23a45d6320b656c05d1,157,251,144,2...
1    a70ef490035d4155e87121c74e8a1498,158,177,190,1...
2    5e94227aceb259ee59ec10a757a16f85,161,98,177,17...
3    5aa478e66f3a1caaaf314b17b211fe7f,158,177,190,1...
4    5af1f370b345ddc8b380f5a5bf37bb55,161,98,177,17...
..                                                 ...
954  c96c4475a384efe118af518c1657164f,157,251,144,2...
955  610994841c89a70b81c4013596916605,157,251,144,2...
956  2d305bd64a1deedaeceeee0e8a93c583,157,251,144,2...
957  85e4404b6fee507579df8c23fc22e2a2,229,229,229,1...
958  95a6d384aafd0f0ee52d9045fbae03e3,229,229,229,1...

[959 rows x 1 columns]

In [32]:
df = df[0].str.split(',', expand=True)
df

,0,1,2,3,4,5,6,7,8,9,...,856305,856306,856307,856308,856309,856310,856311,856312,856313,856314
0,06f73f2da4ecd23a45d6320b656c05d1,157,251,144,205,140,139,157,172,157,...,None,None,None,None,None,None,None,None,None,None
1,a70ef490035d4155e87121c74e8a1498,158,177,190,158,177,190,158,138,139,...,None,None,None,None,None,None,None,None,None,None
2,5e94227aceb259ee59ec10a757a16f85,161,98,177,178,140,139,230,139,232,...,None,None,None,None,None,None,None,None,None,None
3,5aa478e66f3a1caaaf314b17b211fe7f,158,177,190,158,177,190,158,138,139,...,None,None,None,None,None,None,None,None,None,None
4,5af1f370b345ddc8b380f5a5bf37bb55,161,98,177,178,140,139,230,139,232,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954,c96c4475a384efe118af518c1657164f,157,251,144,205,140,139,157,172,157,...,None,None,None,None,None,None,None,None,None,None
955,610994841c89a70b81c4013596916605,157,251,144,205,140,139,157,172,157,...,None,None,None,None,None,None,None,None,None,None
956,2d305bd64a1deedaeceeee0e8a93c583,157,251,144,205,140,139,157,172,157,...,None,None,None,None,None,None,None,None,None,None
957,85e4404b6fee507579df8c23fc22e2a2,229,229,229,177,190,158,177,190,158,...,None,None,None,None,None,None,None,None,None,None
958,95a6d384aafd0f0ee52d9045fbae03e3,229,229,229,177,190,158,177,190,158,...,None,None,None,None,None,None,None,None,None,None

In [36]:
def remove_columns_with_high_missing(df, threshold=0.5):
  """Removes columns with missing values above a specified threshold.

  Args:
    df: The pandas DataFrame.
    threshold: The maximum allowed proportion of missing values.

  Returns:
    A new DataFrame with columns having less than the threshold of missing values.
  """

  missing_percentage = df.isnull().sum() / len(df)
  columns_to_drop = missing_percentage[missing_percentage > threshold].index
  return df.drop(columns_to_drop, axis=1)

# Example usage:
df = remove_columns_with_high_missing(df, threshold=0.5)

In [37]:
df

,0,1,2,3,4,5,6,7,8,9,...,7662,7663,7664,7665,7666,7667,7668,7669,7670,7671
0,06f73f2da4ecd23a45d6320b656c05d1,157,251,144,205,140,139,157,172,157,...,None,None,None,None,None,None,None,None,None,None
1,a70ef490035d4155e87121c74e8a1498,158,177,190,158,177,190,158,138,139,...,158,178,190,187,158,178,190,187,158,178
2,5e94227aceb259ee59ec10a757a16f85,161,98,177,178,140,139,230,139,232,...,214,214,214,214,214,214,214,214,214,214
3,5aa478e66f3a1caaaf314b17b211fe7f,158,177,190,158,177,190,158,138,139,...,233,233,216,229,233,233,216,229,233,233
4,5af1f370b345ddc8b380f5a5bf37bb55,161,98,177,178,140,139,230,139,232,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954,c96c4475a384efe118af518c1657164f,157,251,144,205,140,139,157,172,157,...,97,97,97,97,97,97,97,97,50,97
955,610994841c89a70b81c4013596916605,157,251,144,205,140,139,157,172,157,...,251,140,251,139,22,251,140,251,139,22
956,2d305bd64a1deedaeceeee0e8a93c583,157,251,144,205,140,139,157,172,157,...,None,None,None,None,None,None,None,None,None,None
957,85e4404b6fee507579df8c23fc22e2a2,229,229,229,177,190,158,177,190,158,...,None,None,None,None,None,None,None,None,None,None
958,95a6d384aafd0f0ee52d9045fbae03e3,229,229,229,177,190,158,177,190,158,...,None,None,None,None,None,None,None,None,None,None

In [38]:
df.to_csv('mulware.csv', index=False)